In [3]:
M = np.ones((2,3))

In [4]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
a = np.arange(3)

In [6]:
a

array([0, 1, 2])

In [7]:
a+M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [8]:
a4 = np.arange(1, 4, 1)

In [9]:
a4

array([1, 2, 3])

In [21]:
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a2

array([[0.57561063],
       [0.44792029],
       [0.32435702],
       [0.84198115]])

In [22]:
a3

array([[1, 2, 3, 4]])

In [25]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a1

array([0.44144943, 0.01360986, 0.31563706, 0.64749203])

In [26]:
a2

array([[0.74260922],
       [0.67904824],
       [0.47969208],
       [0.60598281]])

In [27]:
a5 = np.linspace(1 ,4, 4)

In [28]:
a5

array([1., 2., 3., 4.])

In [29]:
a5.shape == a1.shape

True

In [30]:
a3.shape == a4.shape

False

In [32]:
old = np.array([[1, 1, 1], [1, 1, 1]])
old

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
new = old
new

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [43]:
whatever = np.ones((5,5))
whatever

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
whatever[2:4,2:4]

array([[1., 1.],
       [1., 1.]])

In [49]:
s = 'ACBCAC'

In [57]:
re.findall('^AC',s)

['AC']

In [60]:
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

In [78]:
result

['A', 'AA', 'AA', 'AA', 'A']

In [79]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''

In [80]:
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4
